name: 'Prepare signing'
description: 'Prepare signing of the iOS application'
inputs:
  appStoreConnectPrivateKey:
    description: ''
    required: true
  keyID:
    description: ''
    required: true
  issuerID:
    description: ''
    required: true
  keychainName:
    description: 'Id of the newly created temporary kechain'
    required: true
    default: 'signing.ios'
  keychainPassword:
    description: 'Password of the newly created temporary kechain'
    required: true
    default: 'signing.ios'
  base64P12File:
    description: 'Base64 encoded .p12 signing cert with private key'
    required: true
  p12Password:
    description: 'Password of the .p12 file'
    required: true
  bundleIdentifier:
    description: 'Bundle identifier of the application'
    required: true
  signType:
    description: ''
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'shield'
  color: 'orange'
